### ISSUE TITLE
No Navigator file.

### ISSUE THREAD

**Issue by feni-brian** [craftzdog/react-native-animated-todo#13]
In the current `App.tsx` file, there’s this 
```typescript-react
import React from "react";
import AppContainer from "./src/components/app-container";
import Navigator from "./src/";

export default function App() {
  return (
    <AppContainer>
      <Navigator />
    </AppContainer>
  );
}
```
On line 3 where we have to import `Navigator`, the file doesn't actually exist in the `./src/` directory. Was it a syntactical error, or missing file in the right repository, or I’m I missing my head for once, or all at the same time? 
Grateful for the help!

**Comment by enescomruk72** [comment]
In the importing process, if a direct js-jsx file name is not specified, the compiler first looks at the js-jsx file named index in the specified folder. So you don't need to specify it extra @feni-brian

**Comment by feni-brian** [comment]
I did get it work by simply renaming the export file name in the `index.js` file to as `Navigator` such that I could import it as shown earlier. Nevertheless, thanks for the additional insight. Tried your suggestion and works just as well as intended.
Thanks 👍 ...
