### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by MartinezNunezMarcoAntonio** [craftzdog/react-native-animated-todo#5]
after to run application yarn start and select mobile option it works, but after to test 
yarn web, I get an error 
`TypeError: Cannot convert undefined or null to object
useAnimatedStyle
node_modules/react-native-reanimated/lib/reanimated2/Hooks.js:332`

Archlinux base
node v12

**Comment by craftzdog** [comment]
web is not supported
